spring:
  application:
    name: beautysaas
  datasource:
    url: jdbc:postgresql://localhost:5432/beautysaas_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development, 'none' or 'validate' for production
    show-sql: true # Set to false in production
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Spring Security configuration
  security:
    user:
      name: admin
      password: admin

# JWT Configuration
app:
  jwt-secret: YourSuperSecretKeyThatIsAtLeast256BitsLongAndShouldBeStoredSecurelyInProductionEnvironment
  jwt-expiration-milliseconds: 604800000 # 7 days in milliseconds (7 * 24 * 60 * 60 * 1000)

# Security Configuration
security:
  account-lockout:
    max-attempts: 5
    lockout-duration-minutes: 30
  password:
    min-length: 8
    require-uppercase: true
    require-lowercase: true
    require-digits: true
    require-special-chars: true
  session:
    max-concurrent-sessions: 3
    prevent-session-fixation: true

# Server Port
server:
  port: 8080

# Logging configuration
logging:
  level:
    com.example.beautysaas: DEBUG # Set to INFO or WARN in production
    org.springframework.web: INFO
    org.hibernate: INFO

# Audit Trail Configuration
audit:
  retention:
    enabled: true
    schedule: "0 0 1 * * ?" # 1 AM every day
    retention-months: 6 # Keep 6 months of regular logs
    critical-retention-months: 24 # Keep 24 months of critical security events
    batch-size: 1000 # Number of records to process in each batch
